package com.aibot;

import java.io.*;
import java.util.*;

/**
 * Persistent long-term conversation memory.
 * Stores exchanges plus compact embeddings generated by the local NeuralNetwork.
 * Retrieval is similarity-based; it is not injected into every turn.
 */
public class CognitiveMemory {
    public static class Entry {
        public long time;
        public String user;
        public String response;
        public String source;
        public float[] embedding;

        Entry(long time, String user, String response, String source, float[] embedding) {
            this.time = time;
            this.user = user;
            this.response = response;
            this.source = source;
            this.embedding = embedding;
        }
    }

    private static final int MAX_ITEMS = 600;
    private final File file;
    private final NeuralNetwork nn;
    private final Tokenizer tokenizer;
    private final List<Entry> entries = new ArrayList<>();

    public CognitiveMemory(File baseDir, NeuralNetwork nn, Tokenizer tokenizer) {
        if (!baseDir.exists()) baseDir.mkdirs();
        this.file = new File(baseDir, "conversation_memory.bin");
        this.nn = nn;
        this.tokenizer = tokenizer;
        load();
    }

    public synchronized void remember(String user, String response, String source) {
        if (user == null || user.trim().isEmpty() || response == null || response.trim().isEmpty()) return;
        float[] embedding = nn != null && tokenizer != null
            ? nn.embedText(user + " " + response, tokenizer)
            : null;
        entries.add(new Entry(System.currentTimeMillis(), user.trim(), response.trim(),
                source == null ? "conversation" : source, embedding));
        while (entries.size() > MAX_ITEMS) entries.remove(0);
        if (!"dataset".equals(source) || entries.size() % 20 == 0) save();
    }

    public synchronized List<Entry> search(String query, int limit) {
        List<Entry> result = new ArrayList<>();
        if (query == null || query.trim().isEmpty() || entries.isEmpty()) return result;
        float[] q = nn != null && tokenizer != null ? nn.embedText(query, tokenizer) : null;
        List<Scored> scored = new ArrayList<>();
        for (Entry e : entries) {
            float score = cosine(q, e.embedding);
            if (score <= 0.05f) score = lexicalScore(query, e.user);
            scored.add(new Scored(e, score));
        }
        scored.sort((a, b) -> Float.compare(b.score, a.score));
        for (int i = 0; i < Math.min(limit, scored.size()); i++) {
            if (scored.get(i).score > 0.12f) result.add(scored.get(i).entry);
        }
        return result;
    }

    public synchronized String buildContext(String query, int limit) {
        List<Entry> found = search(query, limit);
        if (found.isEmpty()) return "";
        StringBuilder sb = new StringBuilder();
        for (Entry e : found) {
            if (sb.length() > 0) sb.append("\n");
            sb.append("Earlier conversation: User said: ").append(e.user)
              .append(" Assistant replied: ").append(e.response);
        }
        return sb.toString();
    }

    public synchronized String answerMemoryQuestion(String query) {
        String q = query.toLowerCase(Locale.US);
        if (!(q.contains("remember") || q.contains("last time") || q.contains("what did i")
                || q.contains("what we talked") || q.contains("what i said"))) return null;
        List<Entry> found = search(query, 3);
        if (found.isEmpty()) return "I don't have a matching conversation in my saved memory.";
        Entry e = found.get(0);
        return "I remember this: you said "" + e.user + "" and I replied "" + e.response + "".";
    }

    public synchronized void flush() { save(); }

    public synchronized int size() { return entries.size(); }

    public synchronized String getStats() {
        return "Conversation memory: " + entries.size() + " saved exchanges";
    }

    public synchronized void clear() {
        entries.clear();
        if (file.exists()) file.delete();
    }

    private static class Scored {
        Entry entry; float score;
        Scored(Entry entry, float score) { this.entry = entry; this.score = score; }
    }

    private float cosine(float[] a, float[] b) {
        if (a == null || b == null || a.length == 0 || a.length != b.length) return 0f;
        float dot = 0f, na = 0f, nb = 0f;
        for (int i = 0; i < a.length; i++) {
            dot += a[i] * b[i];
            na += a[i] * a[i];
            nb += b[i] * b[i];
        }
        if (na <= 1e-8f || nb <= 1e-8f) return 0f;
        return dot / ((float)Math.sqrt(na) * (float)Math.sqrt(nb));
    }

    private float lexicalScore(String query, String text) {
        Set<String> q = new HashSet<>(Arrays.asList(query.toLowerCase(Locale.US).split("\\W+")));
        Set<String> t = new HashSet<>(Arrays.asList(text.toLowerCase(Locale.US).split("\\W+")));
        q.remove(""); t.remove("");
        if (q.isEmpty() || t.isEmpty()) return 0f;
        int hit = 0;
        for (String w : q) if (t.contains(w)) hit++;
        return (float) hit / q.size();
    }

    private synchronized void save() {
        File tmp = new File(file.getParentFile(), file.getName() + ".part");
        try (DataOutputStream out = new DataOutputStream(new BufferedOutputStream(new FileOutputStream(tmp)))) {
            out.writeInt(2);
            out.writeInt(entries.size());
            for (Entry e : entries) {
                out.writeLong(e.time);
                out.writeUTF(e.user);
                out.writeUTF(e.response);
                out.writeUTF(e.source == null ? "" : e.source);
                if (e.embedding == null) {
                    out.writeInt(0);
                } else {
                    out.writeInt(e.embedding.length);
                    for (float v : e.embedding) out.writeFloat(v);
                }
            }
            out.flush();
            out.close();
            if (!tmp.renameTo(file)) {
                if (file.exists()) file.delete();
                tmp.renameTo(file);
            }
        } catch (Exception ignored) {}
    }

    private void load() {
        if (!file.exists()) return;
        try (DataInputStream in = new DataInputStream(new BufferedInputStream(new FileInputStream(file)))) {
            int version = in.readInt();
            int count = Math.min(in.readInt(), MAX_ITEMS);
            for (int i = 0; i < count; i++) {
                long time = in.readLong();
                String user = in.readUTF();
                String response = in.readUTF();
                String source = in.readUTF();
                int dim = in.readInt();
                float[] emb = dim > 0 && dim < 4096 ? new float[dim] : null;
                if (emb != null) for (int d = 0; d < dim; d++) emb[d] = in.readFloat();
                entries.add(new Entry(time, user, response, source, emb));
            }
        } catch (Exception ignored) {
            entries.clear();
        }
    }
}
